### PR TITLE
divided fields into fieldsets; added initial data; added tooltip about server input dependencies

### LINKED ISSUE #130: Tidy up the main UI form
I think the form might use some grouping and tidying up as it became a bit chaotic.
Maybe something along these lines:

Group 1, build settings: Scala 2 / 3 toggle, sbt / Scala CLI toggle (by default: 3 & sbt)
Group 2, project name & group ID. Maybe we should have defaults here as well (such as: com.softwaremill / my-tapir - or sth auto-generated like curious-badger ;) ) so that generating a project can be even quicker if somebody just wants to explore?
Group 3: effect & server, if we would go with the something-chosen-by-default route, IO + http4s is a good choice
Group 4: options, swagger / json / metrics

### PR DESCRIPTION
**Pull request by tpacuszkapl**
also increased the spacing between section header and text fields, and changed color of fieldset headers to secondary as suggested in #130.

closes #130

### CODE REVIEW

**Comment by adamw** [comment]
thanks - some frontend tests seem to be failing though

**Comment by tpacuszkapl** [comment]
Ah, right. I will fix it today.

**Comment by tpacuszkapl** [comment]
I've fixed the tests. Also, the screen, because I forgot to add it before:
current

**Comment by adamw** [comment]
Awesome, thanks! :)

**Pull request merged**
